openapi: 3.0.3
info:
  title: University - OpenAPI 3.0
  description: |-
    Sample yaml for documentation
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://university.swagger.io/api/v1
tags:
  - name: user
    description: Everything about your Users
paths:
  /user:
    post:
      tags:
        - user
      summary: Add a new User in University
      description: Add a new User in University
      operationId: addUser
      requestBody:
        description: Create a new user in university
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - write:user
            - read:user
  /user/{id}:
    get:
      tags:
        - user
      summary: Find user by ID
      description: Returns a single User
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: ID of user to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
      security:
        - api_key: []
        - petstore_auth:
            - write:user
            - read:user
components:
  schemas:
    College:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Geetham University
      xml:
        name: college
    User:
      required:
        - name
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Sunil Kumar
        location:
          type: string
          example: Hyderabad
        college:
          $ref: '#/components/schemas/College'
      xml:
        name: user
  requestBodies:
    Pet:
      description: user object that needs to be added to the university
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
        application/xml:
          schema:
            $ref: '#/components/schemas/User'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://university.swagger.io/oauth/authorize
          scopes:
            write:pets: modify user details in your account
            read:pets: read your users
    api_key:
      type: apiKey
      name: api_key
      in: header